# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0



# OPENCV ?= /opt/opencv
# INCDIR = -I$(OPENCV)/include 
# INCDIR += -I./mojo

# CFLAGS += $(INCDIR)


# LDLIBS += -L$(OPENCV)/lib64

# LDFLAGS += \
# 	-lopencv_videostab \
# 	-lopencv_photo \
# 	-lopencv_stitching \
# 	-lopencv_objdetect \
# 	-lopencv_video \
# 	-lopencv_ml \
# 	-lopencv_calib3d \
# 	-lopencv_features2d \
# 	-lopencv_imgcodecs \
# 	-lopencv_highgui \
# 	-lopencv_flann \
# 	-lopencv_imgproc \
# 	-lopencv_core


APPNAME := dwarf_birukee
include $(DRIVERS)/common_bare.mk

